### PR TITLE
Update version to 19.00

### PR DESCRIPTION
**Pull request by abloemert**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by abloemert** [comment]
@conda-forge-admin, please rerender

**Comment by abloemert** [comment]
@conda-forge-admin, please rerender

**Comment by abloemert** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
I have (accidentally) added a 7zip package that has the latest released version (and also builds it from scratch): https://github.com/conda-forge/7zip-feedstock

**Comment by yarikoptic** [comment]
thanks @wolfv !  It even provides `7z` now and more "inline" with `p7zip` package (ported `7zip`) so IMHO very nice.  Tuning our datalad feedstock recipe to use it now.

**Pull request closed without merging**
